UGetADog/Controllers/AdoptingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UGetADog.Controllers
{
    public class AdoptingController : Controller
    {
        // GET: Training
        public ActionResult Index()
        {
            return View();
        }
    }
}

UGetADog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UGetADog!!!!</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UGetADog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @try
                    {
                        if (Session["Role"].ToString() == "Admin")
                        {
                            <li>@Html.ActionLink("User", "Index", "Users")</li>
                            <li>@Html.ActionLink("Giver", "Index", "givers")</li>
                            <li>@Html.ActionLink("Statistics", "AdminIndex", "Dogs")</li>

                        }
                        if (Session["Role"].ToString() != "null")
                        {
                            <li>@Html.ActionLink("My Account", "MyAccount", "Users")</li>
                            <li>@Html.ActionLink("Giver search", "Index", "FullGivers")</li>
                            <li>@Html.ActionLink("Dog Search", "Index", "Dogs")</li>

                        }
                        if (Session["Role"].ToString() == "Giver")
                        {
                            if (Session["GID"].ToString() != null)
                            {
                            <li>@Html.ActionLink("Weather", "Weather", "Givers")</li>
                            }
                        }
                    }
                    catch
                    {
                        <li>@Html.ActionLink("LogIn", "Login", "Users")</li>
                    }

                    <li>@Html.ActionLink("You Should Adopt", "Index", "Adopting")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Created by: Matan,Tamir,Noa and shachar</p>
            <p>Contact information: help@weNeverAnswer.com</p>
            <p>&copy; @DateTime.Now.Year - U get a dog </p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>